name: Go [lint, test]

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '*'
jobs:
  linting:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: ['ubuntu-20.04']
        go: ['1.16']
    runs-on: ${{ matrix.os }}
    name: Run linters
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      
      - name: Vet
        run: |
          make vet
          
      - name: Install tools
        run: |
          make install-vendored-tools
      
      - name: Lint
        run: |
          make lint-pipeline
