name: Lint & Test & Build & Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - "!*"

jobs:
  build:
    runs-on: 'ubuntu-20.04'
    name: Lint & Test & Build & Release
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      
      - name: Vet
        run: |
          make vet
      
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          install-only: true
      
      - name: Run GoReleaser
        if: success()
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
